version: "3"

volumes:
  pg_data:

services:
  db:
    container_name: pageshot_db
    image: ${DB_IMAGE}
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - 5432:5432

  redis:
    container_name: pageshot_redis
    image: ${REDIS_IMAGE}
    restart: on-failure

  bot:
    container_name: pageshot_bot
    build: .
    env_file: .env
    depends_on:
      - db
      - redis
    command: sh -c "sleep 10 && alembic upgrade head && python -m app"
    restart: on-failure
  
  # celery:
  #   container_name: pageshot-celery
  #   image: pageshot-backend
  #   env_file: .env
  #   command: sh -c "celery -A app.worker.celery:celery_worker worker -l INFO"
  #   depends_on:
  #     - redis